openbookqa:
  - gl: proxectonos/openbookqa_gl
  - en: cnut1648/openbookqa_retrieved_by_colbert
  - cat: projecte-aina/openbookqa_ca
  - es: BSC-LT/openbookqa-es
  - pt: proxectonos/pt_OpenBookQA_test

belebele:
  - gl: proxectonos/belebele_gl
  - en: [facebook/belebele,eng_Latn]
  - cat: [facebook/belebele,cat_Latn]
  - es: [facebook/belebele,spa_Latn]
  - pt: [facebook/belebele,por_Latn]

veritasqa:
  - gl: [projecte-aina/veritasQA,gl]
  - en: [projecte-aina/veritasQA,en]
  - cat: [projecte-aina/veritasQA,ca]
  - es: [projecte-aina/veritasQA,es]

summarization:
  - gl: /mnt/netapp1/Proxecto_NOS/adestramentos/avaliacion/eval_corpus/summarization/summarization.jsonl

xstoryclose:
  - gl: proxectonos/xstorycloze_gl
  - en: [juletxara/xstory_cloze,en]
  - cat: projecte-aina/xstorycloze_ca
  - es: [juletxara/xstory_cloze,es]
  - pt: proxectonos/xstorycloze_gl
